<option></option>
<option value=" B.Arch " > B.Arch </option>
<option value=" B.A.     " > B.A.     </option>
<option value=" B.A.M.S.     " > B.A.M.S.     </option>
<option value=" B.B.A. " > B.B.A. </option>
<option value=" B.Com. " > B.Com. </option>
<option value=" B.C.A. " > B.C.A. </option>
<option value=" B.D.S. " > B.D.S. </option>
<option value=" B.Des. / B.D. " > B.Des. / B.D. </option>
<option value=" B.Ed. " > B.Ed. </option>
<option value=" B.E./B.Tech. " > B.E./B.Tech. </option>
<option value=" BFA / BVA " > BFA / BVA </option>
<option value=" B.F.Sc./ B.Sc. (Fisheries). " > B.F.Sc./ B.Sc. (Fisheries). </option>
<option value=" B.H.M.S. " > B.H.M.S. </option>
<option value=" L.L.B. " > L.L.B. </option>
<option value=" B.Lib. / B.Lib.Sc. " > B.Lib. / B.Lib.Sc. </option>
<option value=" B.M.C. / B.M.M. " > B.M.C. / B.M.M. </option>
<option value=" M.B.B.S. " > M.B.B.S. </option>
<option value="" ></option>
<option value=" B.Pharm / B.Pharma. " > B.Pharm / B.Pharma. </option>
<option value=" B.P.Ed. " > B.P.Ed. </option>
<option value=" B.P.T. " > B.P.T. </option>
<option value=" B.Sc. " > B.Sc. </option>
<option value=" BSW / B.A. (SW) " > BSW / B.A. (SW) </option>
<option value=" B.V.Sc. & A.H. / B.V.Sc " > B.V.Sc. & A.H. / B.V.Sc </option>
<option value=" M.D. " > M.D. </option>
<option value=" M.D. (Homoeopathy) " > M.D. (Homoeopathy) </option>
<option value=" Pharm.D     " > Pharm.D     </option>
<option value=" Ph.D. " > Ph.D. </option>
<option value=" D.M. " > D.M. </option>
<option value=" M.Arch. " > M.Arch. </option>
<option value=" M.A. " > M.A. </option>
<option value=" M.B.A. " > M.B.A. </option>
<option value=" M.Ch. " > M.Ch. </option>
<option value=" M.Com.     " > M.Com.     </option>
<option value=" M.C.A. " > M.C.A. </option>
<option value=" M.D.S. " > M.D.S. </option>
<option value=" M.Des./ M.Design. " > M.Des./ M.Design. </option>
<option value=" M.Ed. " > M.Ed. </option>
<option value=" M.E./ M.Tech. " > M.E./ M.Tech. </option>
<option value=" MFA / MVA " > MFA / MVA </option>
<option value=" L.L.M. " > L.L.M. </option>
<option value=" M.Lib./ M.Lib.Sc. " > M.Lib./ M.Lib.Sc. </option>
<option value=" M.M.C / M.M.M. " > M.M.C / M.M.M. </option>
<option value=" M.Pharm     " > M.Pharm     </option>
<option value=" M.Phil.     " > M.Phil.     </option>
<option value="" ></option>
<option value=" M.P.T. " > M.P.T. </option>
<option value=" M.Sc. " > M.Sc. </option>
<option value=" M.S.W. / M.A. (SW) " > M.S.W. / M.A. (SW) </option>
<option value=" M.Sc. (Agriculture) " > M.Sc. (Agriculture) </option>
<option value=" M.S. " > M.S. </option>
<option value=" M.V.Sc. " > M.V.Sc. </option>
<option value=" B.Arch " >Bachelor of Architecture </option>
<option value=" B.A.     " >Bachelor of Arts </option>
<option value=" B.A.M.S.     " >Bachelor of Ayurvedic Medicine & Surgery </option>
<option value=" B.B.A. " >Bachelor of Business Administration </option>
<option value=" B.Com. " >Bachelor of Commerce </option>
<option value=" B.C.A. " >Bachelor of Computer Applications </option>
<option value=" B.D.S. " >Bachelor of Dental Surgery </option>
<option value=" B.Des. / B.D. " >Bachelor of Design </option>
<option value=" B.Ed. " >Bachelor of Education </option>
<option value=" B.E./B.Tech. " >Bachelor of Engineering / Bachelor of Technology </option>
<option value=" BFA / BVA " >Bachelor of Fine Arts </option>
<option value=" B.F.Sc./ B.Sc. (Fisheries). " >Bachelor of Fisheries Science </option>
<option value=" B.H.M.S. " >Bachelor of Homoeopathic Medicine and Surgery </option>
<option value=" L.L.B. " >Bachelor of Laws </option>
<option value=" B.Lib. / B.Lib.Sc. " >Bachelor of Library Science </option>
<option value=" B.M.C. / B.M.M. " >Bachelor of Mass Communications </option>
<option value=" M.B.B.S. " >Bachelor of Medicine and Bachelor of Surgery </option>
<option value="" ></option>
<option value=" B.Pharm / B.Pharma. " >Bachelor of Pharmacy </option>
<option value=" B.P.Ed. " >Bachelor of Physical Education </option>
<option value=" B.P.T. " >Bachelor of Physiotherapy </option>
<option value=" B.Sc. " >Bachelor of Science </option>
<option value=" BSW / B.A. (SW) " >Bachelor of Social Work </option>
<option value=" B.V.Sc. & A.H. / B.V.Sc " >Bachelor of Veterinary Science & Animal Husbandry </option>
<option value=" M.D. " >Doctor of Medicine </option>
<option value=" M.D. (Homoeopathy) " >Doctor of Medicine in Homoeopathy </option>
<option value=" Pharm.D     " >Doctor of Pharmacy </option>
<option value=" Ph.D. " >Doctor of Philosophy </option>
<option value=" D.M. " >Doctorate of Medicine </option>
<option value=" M.Arch. " >Master of Architecture </option>
<option value=" M.A. " >Master of Arts </option>
<option value=" M.B.A. " >Master of Business Administration </option>
<option value=" M.Ch. " >Master of Chirurgiae </option>
<option value=" M.Com.     " >Master of Commerce </option>
<option value=" M.C.A. " >Master of Computer Applications </option>
<option value=" M.D.S. " >Master of Dental Surgery </option>
<option value=" M.Des./ M.Design. " >Master of Design </option>
<option value=" M.Ed. " >Master of Education </option>
<option value=" M.E./ M.Tech. " >Master of Engineering / Master of Technology </option>
<option value=" MFA / MVA " >Master of Fine Arts </option>
<option value=" L.L.M. " >Master of Laws </option>
<option value=" M.Lib./ M.Lib.Sc. " >Master of Library Science </option>
<option value=" M.M.C / M.M.M. " >Master of Mass Communications / Mass Media </option>
<option value=" M.Pharm     " >Master of Pharmacy </option>
<option value=" M.Phil.     " >Master of Philosophy </option>
<option value="" ></option>
<option value=" M.P.T. " >Master of Physiotherapy </option>
<option value=" M.Sc. " >Master of Science </option>
<option value=" M.S.W. / M.A. (SW) " >Master of Social Work / Master of Arts in Social Work </option>
<option value=" M.Sc. (Agriculture) " >Master of Science in Agriculture </option>
<option value=" M.S. " >Master of Surgery </option>
<option value=" M.V.Sc. " >Master of Veterinary Science </option>
<option value=" B.Arch " > BArch </option>
<option value=" B.A.     " > BA     </option>
<option value=" B.A.M.S.     " > BAMS     </option>
<option value=" B.B.A. " > BBA </option>
<option value=" B.Com. " > BCom </option>
<option value=" B.C.A. " > BCA </option>
<option value=" B.D.S. " > BDS </option>
<option value=" B.Des. / B.D. " > BDes / BD </option>
<option value=" B.Ed. " > BEd </option>
<option value=" B.E./B.Tech. " > BE/BTech </option>
<option value=" BFA / BVA " > BFA / BVA </option>
<option value=" B.F.Sc./ B.Sc. (Fisheries). " > BFSc/ BSc (Fisheries) </option>
<option value=" B.H.M.S. " > BHMS </option>
<option value=" L.L.B. " > LLB </option>
<option value=" B.Lib. / B.Lib.Sc. " > BLib / BLibSc </option>
<option value=" B.M.C. / B.M.M. " > BMC / BMM </option>
<option value=" M.B.B.S. " > MBBS </option>
<option value="" ></option>
<option value=" B.Pharm / B.Pharma. " > BPharm / BPharma </option>
<option value=" B.P.Ed. " > BPEd </option>
<option value=" B.P.T. " > BPT </option>
<option value=" B.Sc. " > BSc </option>
<option value=" BSW / B.A. (SW) " > BSW / BA (SW) </option>
<option value=" B.V.Sc. & A.H. / B.V.Sc " > BVSc & AH / BVSc </option>
<option value=" M.D. " > MD </option>
<option value=" M.D. (Homoeopathy) " > MD (Homoeopathy) </option>
<option value=" Pharm.D     " > PharmD     </option>
<option value=" Ph.D. " > PhD </option>
<option value=" D.M. " > DM </option>
<option value=" M.Arch. " > MArch </option>
<option value=" M.A. " > MA </option>
<option value=" M.B.A. " > MBA </option>
<option value=" M.Ch. " > MCh </option>
<option value=" M.Com.     " > MCom     </option>
<option value=" M.C.A. " > MCA </option>
<option value=" M.D.S. " > MDS </option>
<option value=" M.Des./ M.Design. " > MDes/ MDesign </option>
<option value=" M.Ed. " > MEd </option>
<option value=" M.E./ M.Tech. " > ME/ MTech </option>
<option value=" MFA / MVA " > MFA / MVA </option>
<option value=" L.L.M. " > LLM </option>
<option value=" M.Lib./ M.Lib.Sc. " > MLib/ MLibSc </option>
<option value=" M.M.C / M.M.M. " > MMC / MMM </option>
<option value=" M.Pharm     " > MPharm     </option>
<option value=" M.Phil.     " > MPhil     </option>
<option value="" ></option>
<option value=" M.P.T. " > MPT </option>
<option value=" M.Sc. " > MSc </option>
<option value=" M.S.W. / M.A. (SW) " > MSW / MA (SW) </option>
<option value=" M.Sc. (Agriculture) " > MSc (Agriculture) </option>
<option value=" M.S. " > MS </option>
<option value=" M.V.Sc. " > MVSc </option>